sudo: required
language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

env:
  matrix:
  - DJANGO_VERSION=1.11.7
  - DJANGO_VERSION=dev

matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION=dev

install:
   # This is a dependency of our Django test script
 - pip install argparse
 - if [[ $DJANGO_VERSION == dev ]]; then pip
   install https://github.com/django/django/tarball/master/django.tar.gz#egg=django; else pip
   install -q Django==$DJANGO_VERSION; fi

 - pip install coverage
 - pip install flake8

 - python setup.py develop

 - pip freeze
 - dpkg -l

before_script:
 - flake8 --ignore=E501 leaflet

script:
 - python quicktest.py jstree

after_success:
 - coverage run quicktest.py leaflet --db=$DATABASE
 - pip install coveralls
 - coveralls